modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mixins]]
config="vestalihy.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="createbigcannons"
    type="optional"
    versionRange="[0.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"